### ISSUE TITLE
7. Deployment

### ISSUE THREAD

**Issue by Anne-Bee** [Anne-Bee/PortfolioWebsite#7]
## Acceptance Criteria:

- The website is live at a GitHub Pages URL.
- All links, images, and assets load correctly in the production build.
- The build is optimized for performance.

## To-Do List:

- [ ] Build the project using ng build --prod.
- [ ] Install the Angular CLI deployment package: 
```
ng add angular-cli-ghpages
``` 

- [ ] Deploy to GitHub Pages
```
ng deploy --base-href=/portfolio-website/
```

- [ ] Verify the deployment by accessing the live URL.
